logging:
  level:
    root: INFO
    org:
      apache:
        kafka: WARN
spring:
  application:
    name: ID
  profiles:
    active: ${ENV:dev}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
  datasource:
    url: ${MASTER_DATABASE_URL:jdbc:postgresql://localhost:5455/postgres}
    username: ${MASTER_DATABASE_USER:postgresUser}
    password: ${MASTER_DATABASE_PWD:postgresPW}
    driver-class-name: org.postgresql.Driver
initialization:
  email: teacher@example.com
  password: 12345678
common:
  security:
    cors:
      allowed-origins: ${CORS_ORIGINS:http://localhost:8080, http://localhost:3000}
      allowed-methods: ${CORS_METHODS:*}
      allowed-headers: ${CORS_HEADERS:*}
    path-matcher:
      permit-all-path-patterns:
        - /api/v1/auth/**
        - /webjars/swagger-ui/**
        - /v3/api-docs/**
        - /swagger-resources/**
        - /webjars/**
        - /swagger-ui/**
        - /swagger-ui.html
        - /null/swagger-resources/**
        - /actuator/**
      permit-all-path-pattern-with-role:
        student:
          pattern: /api/v1/student/**
          role: S
        teacher:
          pattern: /api/v1/teacher/**
          role: T

